from __future__ import annotations
import json
import networkx as nx
from networkx.readwrite import json_graph


def to_json(G: nx.Graph, communities: dict[int, list[str]], output_path: str) -> None:
    node_community = {n: cid for cid, nodes in communities.items() for n in nodes}
    data = json_graph.node_link_data(G, edges="links")
    for node in data["nodes"]:
        node["community"] = node_community.get(node["id"])
    with open(output_path, "w") as f:
        json.dump(data, f, indent=2)


def to_cypher(G: nx.Graph, output_path: str) -> None:
    lines = ["// Neo4j Cypher import — generated by /graphify", ""]
    for node_id, data in G.nodes(data=True):
        label = data.get("label", node_id).replace("'", "\\'")
        ftype = data.get("file_type", "unknown").capitalize()
        lines.append(f"MERGE (n:{ftype} {{id: '{node_id}', label: '{label}'}});")
    lines.append("")
    for u, v, data in G.edges(data=True):
        rel = data.get("relation", "RELATES_TO").upper().replace(" ", "_").replace("-", "_")
        conf = data.get("confidence", "EXTRACTED")
        lines.append(
            f"MATCH (a {{id: '{u}'}}), (b {{id: '{v}'}}) "
            f"MERGE (a)-[:{rel} {{confidence: '{conf}'}}]->(b);"
        )
    with open(output_path, "w") as f:
        f.write("\n".join(lines))
